version: '3.1'
services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./relational_db:/docker-entrypoint-initdb.d  
    entrypoint: docker-entrypoint.sh postgres -c max_connections=100

  website:
    image: nginx  
    container_name: forum-website
    volumes:
      - ./app:/usr/share/nginx/html  
    ports:
      - "80:80" 