version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: dbpw
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_docker
    ports:
      - "5432:5432"
    volumes:
      - ./relational_db:/docker-entrypoint-initdb.d  
    entrypoint: docker-entrypoint.sh postgres -c max_connections=100

  website:
    image: nginx
    container_name: forum-website
    volumes:
      - ./app/website:/usr/share/nginx/html  
    ports:
      - "80:80"
    

  nodejs-api:
    build: .
    container_name: nodejs-api
    ports:
      - "3000:3000" 